yatm_papercraft:require("items/paper.lua")
yatm_papercraft:require("items/cardboard.lua")
yatm_papercraft:require("items/waxed_cardboard.lua")
yatm_papercraft:require("items/fluid_box.lua")
yatm_papercraft:require("items/painting_brush.lua")
