yatm_decor:require("nodes/jukebox.lua")
yatm_decor:require("nodes/lamp.lua")
yatm_decor:require("nodes/warning_checkers.lua")
yatm_decor:require("nodes/warning_stripes.lua")
yatm_decor:require("nodes/meshes.lua")
yatm_decor:require("nodes/vents.lua")
