dofile(yatm_decor.modpath .. "/nodes/jukebox.lua")
dofile(yatm_decor.modpath .. "/nodes/lamp.lua")
dofile(yatm_decor.modpath .. "/nodes/warning_checkers.lua")
dofile(yatm_decor.modpath .. "/nodes/warning_stripes.lua")
dofile(yatm_decor.modpath .. "/nodes/meshes.lua")
dofile(yatm_decor.modpath .. "/nodes/vents.lua")
