yatm_rails:require("/entities/battery_cart.lua")
yatm_rails:require("/entities/item_cart.lua")
yatm_rails:require("/entities/fluid_cart.lua")
yatm_rails:require("/entities/solid_fuel_locomotive.lua")
yatm_rails:require("/entities/electric_locomotive.lua")
