yatm_rails:require("/nodes/sensor_rails.lua")
yatm_rails:require("/nodes/data_rails.lua")
yatm_rails:require("/nodes/docking_station.lua")
yatm_rails:require("/nodes/battery_cart_loader.lua")
yatm_rails:require("/nodes/fluid_cart_loader.lua")
yatm_rails:require("/nodes/item_cart_loader.lua")
