yatm_spacetime:require("nodes/teleporter.lua")
yatm_spacetime:require("nodes/teleporter_relay.lua")
yatm_spacetime:require("nodes/teleporter_port.lua")
yatm_spacetime:require("nodes/teleporter_gate.lua")
yatm_spacetime:require("nodes/teleporter_gate_controller.lua")
