yatm_fluids:require("tests/fluid_containers_test.lua")
yatm_fluids:require("tests/fluid_inventory_registry_test.lua")
yatm_fluids:require("tests/fluid_inventory_test.lua")
yatm_fluids:require("tests/fluid_stack_test.lua")
yatm_fluids:require("tests/fluid_meta_test.lua")
yatm_fluids:require("tests/fluid_registry_test.lua")
yatm_fluids:require("tests/utils_test.lua")
