dofile(yatm_fluids.modpath .. "/tests/fluid_inventory_registry_test.lua")
dofile(yatm_fluids.modpath .. "/tests/fluid_inventory_test.lua")
dofile(yatm_fluids.modpath .. "/tests/fluid_stack_test.lua")
dofile(yatm_fluids.modpath .. "/tests/fluid_meta_test.lua")
dofile(yatm_fluids.modpath .. "/tests/fluid_registry_test.lua")
dofile(yatm_fluids.modpath .. "/tests/utils_test.lua")
