name = yatm_oku_emu_6502
description = Adds the MOS6502 emulation for YATM OKU
depends = foundation_base,foundation_buffer,foundation_class,foundation_stdlib,foundation_utf8,yatm_oku
optional_depends = yatm_prelude
