yatm_armoury:require("nodes/ammo_can.lua")
yatm_armoury:require("nodes/turret_base.lua")
yatm_armoury:require("nodes/belt_loader.lua")
yatm_armoury:require("nodes/chemical_injector.lua")
yatm_armoury:require("nodes/magazine_loader.lua")
yatm_armoury:require("nodes/target.lua")
