yatm_brewery:require("nodes/fluid_barrel.lua")
yatm_brewery:require("nodes/aging_barrel.lua")
yatm_brewery:require("nodes/kettle.lua")
yatm_brewery:require("nodes/basin.lua")
yatm_brewery:require("nodes/mechanical_press.lua")
