dofile(yatm_foundry.modpath .. "/nodes/concrete.lua")
dofile(yatm_foundry.modpath .. "/nodes/carbon_steel_block.lua")

dofile(yatm_foundry.modpath .. "/nodes/electric_heater.lua")
dofile(yatm_foundry.modpath .. "/nodes/electric_furnace.lua")
dofile(yatm_foundry.modpath .. "/nodes/electric_kiln.lua")
dofile(yatm_foundry.modpath .. "/nodes/electric_smelter.lua")
dofile(yatm_foundry.modpath .. "/nodes/electric_molder.lua")
dofile(yatm_foundry.modpath .. "/nodes/stonecutters_table.lua")
dofile(yatm_foundry.modpath .. "/nodes/mini_blast_furnace.lua")
dofile(yatm_foundry.modpath .. "/nodes/solid_fuel_heater.lua")
dofile(yatm_foundry.modpath .. "/nodes/smelter.lua")
dofile(yatm_foundry.modpath .. "/nodes/furnace.lua")
dofile(yatm_foundry.modpath .. "/nodes/kiln.lua")
dofile(yatm_foundry.modpath .. "/nodes/molder.lua")
