yatm_foundry:require("nodes/concrete.lua")
yatm_foundry:require("nodes/concrete_wall.lua")
yatm_foundry:require("nodes/retaining_wall.lua")
yatm_foundry:require("nodes/carbon_steel_block.lua")
yatm_foundry:require("nodes/carbon_steel_chest.lua")

yatm_foundry:require("nodes/electric_heater.lua")
yatm_foundry:require("nodes/electric_furnace.lua")
yatm_foundry:require("nodes/electric_kiln.lua")
yatm_foundry:require("nodes/electric_smelter.lua")
yatm_foundry:require("nodes/electric_molder.lua")
yatm_foundry:require("nodes/stonecutters_table.lua")
yatm_foundry:require("nodes/mini_blast_furnace.lua")
yatm_foundry:require("nodes/solid_fuel_heater.lua")
yatm_foundry:require("nodes/smelter.lua")
yatm_foundry:require("nodes/furnace.lua")
yatm_foundry:require("nodes/kiln.lua")
yatm_foundry:require("nodes/molder.lua")
