local mod = assert(yatm_reactors)

mod:require("nodes/control_rod.lua")
mod:require("nodes/data_bus.lua")
mod:require("nodes/energy_bus.lua")
mod:require("nodes/export_bus.lua")
mod:require("nodes/fuel_rod.lua")
mod:require("nodes/glass.lua")
mod:require("nodes/heat_exchanger.lua")
mod:require("nodes/import_bus.lua")
mod:require("nodes/panel.lua")
mod:require("nodes/reactor_controller.lua")
mod:require("nodes/rtg.lua")
