yatm_oku:require("tests/oku/memory_test.lua")
yatm_oku:require("tests/oku/isa/mos_6502_test.lua")
yatm_oku:require("tests/oku/isa/oku_forth_test.lua")
yatm_oku:require("tests/oku_test.lua")
yatm_oku:require("tests/api_test.lua")
