local mod = yatm_machines

mod:require("autotest/models/auto_crafter.lua")
mod:require("autotest/models/auto_grinder.lua")
mod:require("autotest/models/coal_generator.lua")
mod:require("autotest/models/combustion_engine.lua")
mod:require("autotest/models/compactor.lua")
mod:require("autotest/models/condenser.lua")
mod:require("autotest/models/crusher.lua")
mod:require("autotest/models/crystal_cauldron.lua")
mod:require("autotest/models/electrolyser.lua")
mod:require("autotest/models/fluid_nullifier.lua")
mod:require("autotest/models/fluid_replicator.lua")
mod:require("autotest/models/freezer.lua")
mod:require("autotest/models/item_replicator.lua")
mod:require("autotest/models/mixer.lua")
mod:require("autotest/models/network_controller.lua")
mod:require("autotest/models/pylon.lua")
mod:require("autotest/models/roller.lua")
mod:require("autotest/models/server.lua")
mod:require("autotest/models/server_controller.lua")
mod:require("autotest/models/server_rack.lua")
mod:require("autotest/models/steam_turbine.lua")
mod:require("autotest/models/thermal_plate.lua")
