dofile(yatm_bees.modpath .. "/items/bee.lua")
dofile(yatm_bees.modpath .. "/items/bee_box_frame.lua")
dofile(yatm_bees.modpath .. "/items/honey_comb.lua")
dofile(yatm_bees.modpath .. "/items/brood_comb.lua")
dofile(yatm_bees.modpath .. "/items/synthetic_comb.lua")
dofile(yatm_bees.modpath .. "/items/synthetic_brood_comb.lua")
