yatm_bees:require("items/bee.lua")
yatm_bees:require("items/bee_box_frame.lua")
yatm_bees:require("items/honey_comb.lua")
yatm_bees:require("items/brood_comb.lua")
yatm_bees:require("items/synthetic_comb.lua")
yatm_bees:require("items/synthetic_brood_comb.lua")
yatm_bees:require("items/honey_drop.lua")
