local sounds = foundation.com.SoundsRegistry:new()

sounds:register("access_denied", "yatm_access_denied", {})
sounds:register("access_granted", "yatm_beep0", {})
sounds:register("action_close", "yatm_action_close", {})
sounds:register("action_completed", "yatm_action_completed", {})
sounds:register("action_error", "yatm_action_error", {})
sounds:register("action_open", "yatm_action_open", {})
sounds:register("beep", "yatm_beep1", {})
sounds:register("blip0", "yatm_blip0", {})
sounds:register("blip1", "yatm_blip1", {})
sounds:register("boop0", "yatm_boop0", {})
sounds:register("bottle_place", "yatm_bottle_place", {})
sounds:register("button_click", "yatm_button_click", {})
sounds:register("compile_success", "yatm_compile_success", {})
sounds:register("critical_access_denied", "yatm_critical_access_denied", {})
sounds:register("double_boop0", "yatm_double_boop0", {})
sounds:register("hard_read", "yatm_hard_read", {})
sounds:register("heavy_klaxon", "yatm_heavy_klaxon", {})
sounds:register("inventory_place", "yatm_inventory_place", {})
sounds:register("janky_read", "yatm_janky_read", {})
sounds:register("long_error", "yatm_long_error", {})
sounds:register("long_read", "yatm_long_read", {})
sounds:register("machine_open", "yatm_machine_open", {})
sounds:register("move", "yatm_move", {})
sounds:register("not_enough_material", "yatm_not_enough_material", {})
sounds:register("notify", "yatm_notify", {})
sounds:register("ping0", "yatm_ping0", {})
sounds:register("print", "yatm_print", {})
sounds:register("sharp_boop0", "yatm_sharp_boop0", {})
sounds:register("short_circuit", "yatm_short_circuit", {})
sounds:register("stop_read", "yatm_stop_read", {})

yatm_core.sounds = sounds
