yatm_oku:require("lib/oku/isa/riscv.lua")
yatm_oku:require("lib/oku/isa/mos_6502.lua")
yatm_oku:require("lib/oku/isa/oku_forth.lua")
yatm_oku:require("lib/oku/isa/oku_forth8.lua")
yatm_oku:require("lib/oku/isa/oku_forth16.lua")
yatm_oku:require("lib/oku/isa/oku_forth32.lua")
